#! /bin/sh

config_dir="setting"

ln -s -f ~/$config_dir/bash/bashrc ~/.bashrc
ln -s -f ~/$config_dir/vim/ ~/.vim
rm ~/$config_dir/vim/vim # ln's strange action
ln -s -f ~/$config_dir/vim/vimrc ~/.vimrc
ln -s -f ~/$config_dir/script/ ~/script
rm ~/$config_dir/script/script # ln's strange action
ln -s -f ~/$config_dir/tools/ ~/tools
rm ~/$config_dir/tools/tools # ln's strange action
ln -s -f ~/$config_dir/gdb/gdbinit ~/.gdbinit

ln -s -f ~/$config_dir/vim/pathogen/autoload ~/$config_dir/vim/autoload
rm ~/$config_dir/vim/pathogen/autoload/autoload # ln's strange action
echo "DONE"
