set number
set autoindent
set smartindent
set shiftwidth=3
set tabstop=3
set hlsearch

" for split window move
nnoremap <C-Right> <C-w>l
nnoremap <C-Left> <C-w>h
nnoremap <C-Up> <C-w>k
nnoremap <C-Down> <C-w>j

nnoremap a<C-Right> <C-W>L
nnoremap a<C-Left> <C-W>H
nnoremap a<C-Up> <C-W>K
nnoremap a<C-Down> <C-W>J

" for idutils
map <C-\> :!gid <cword> \| less <CR><CR>
map <C-p> :tabe %<CR>

" for ctags
set tags=./tags,../tags,../../tags,../../../tags,../../../../tags,../../../../../tags

" for nerd tree
map <C-n> :NERDTreeToggle<CR>

" for tagbar
map l :TagbarToggle<CR>

" for syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1

"map <C-f> :SyntasticToggleMode<CR>
map <C-f> :YcmDiags<CR>

" for YCM
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_key_list_select_completion = ['', '']
let g:ycm_key_list_previous_completion = ['', '']
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_warning_symbol = '>*'

map <C-g> :YcmCompleter GoTo<CR>
map <C-h> :YcmCompleter GoToImprecise<CR>
map <C-d> :YcmCompleter GoToDeclaration<CR>
"nnoremap <C-t> :YcmCompleter GetType<CR>
map <C-p> :YcmCompleter GetParent<CR>

" for pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

