set number
set autoindent
set smartindent
set shiftwidth=2
set tabstop=2
set hlsearch
set expandtab
set backspace=indent,eol,start
syntax on

" for split window move
nnoremap <C-Right> :wincmd l<CR>
nnoremap <C-Left> :wincmd h<CR>
nnoremap <C-Up> :wincmd k<CR>
nnoremap <C-Down> :wincmd j<CR>
map f<C-Left> :wincmd k<CR>f
map f<C-Right> :wincmd j<CR>f

" for idutils
map <C-\> :!gid <cword> \| less <CR><CR>
map <C-p> :tabe %<CR>

" for ctags
set tags=./tags,../tags,../../tags,../../../tags,../../../../tags,../../../../../tags

" for nerd tree
nnoremap <C-n> :NERDTreeToggle<CR>

" for tagbar
nnoremap <C-l> :TagbarToggle<CR>

" for syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1

"map <C-f> :SyntasticToggleMode<CR>
nnoremap <C-f> :YcmDiags<CR>

" for YCM
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 0
let g:ycm_key_list_select_completion = ['', '']
let g:ycm_key_list_previous_completion = ['', '']
let g:ycm_autoclose_preview_window_after_completion = 1
let g:ycm_warning_symbol = '>*'

nnoremap <C-g> :YcmCompleter GoTo<CR>
nnoremap <C-h> :YcmCompleter GoToImprecise<CR>
nnoremap <C-d> :YcmCompleter GoToDeclaration<CR>
"nnoremap <C-t> :YcmCompleter GetType<CR>
nnoremap <C-p> :YcmCompleter GetParent<CR>

" for pathogen
execute pathogen#infect()

